// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
fooc_path=get_absolute_file_path('loader.sce');
link(fooc_path+'libfooc.dll',['fooc'],'c');
