%save xyz values
function savexyzvrml(filename, nvals, x, y, z, t)


	fd=xmlfile(filename, schemaname, schemahyperlink)
	write "http:%www.web3d.org/specifications/vrml-3.0.dtd", "/www.web3d.org/TaskGroups/vrml/translation/vrml-3.0.dtd"

  opnexml(fd, vrml);
  
  fprintf(fd, 'Group {\n');
  fprintf(fd,'children [\n');

  
  
  
  writevrmlviewpoint(fd);
	%writevrmlnavinfo(fd)
	writevrmldefsphere(fd)
	
	for j=1:nvals
	 		writevrmlobject(fd, x(j), y(j), z(j), t(j))
	end
	
	fprintf(fd,' ]\n');
  fprintf(fd, '}\n');

	
	fclose(fd)
   
  
%endfunction

function writevrmlheader(fd)

	fprintf(fd, '#VRML V2.0 utf8\n')
	fprintf(fd, '# X3D-to-VRML-97 XSL translation autogenerated by X3dToVrml97.xsl\n')
	fprintf(fd, '# http:\/\/www.web3D.org\/TaskGroups\/vrml\/translation\/X3dToVrml97.xsl\n')

	fprintf(fd, '# [X3D] VRML V3.0 utf8\n')

	fprintf(fd, '# [head]\n')
	fprintf(fd, '# [meta] filename: lorenz.vrml\n')
	fprintf(fd, '# [meta] description: Simple X3D example\n')
	fprintf(fd, '# [meta] created: 3 January 2005\n')
	fprintf(fd, '# [meta] revised: 6 March 2003\n')
	fprintf(fd, '# [meta] author: Mike Griffiths\n')
	fprintf(fd, '# [meta] url: http:\/\/www.web3d.org\/TaskGroups\/vrml\/translation\/examples\/HelloWorld.vrml\n')
	fprintf(fd, '# [meta] generator: X3D-Edit, http:\/\/www.web3d.org\/TaskGroups\/vrml\/translation\/README.X3D-Edit.html\n')
	fprintf(fd, '# [Scene]\n')

	fprintf(fd, '# Example scene to illustrate X3D tags and attributes.\n')


%endfunction

function writevrmlviewpoint(fd)
     fprintf(fd, 'Viewpoint {\n');
     %fprintf(fd, 'description "hello, world!"\n');
     fprintf(fd, 'orientation 0 1 0 1.57\n');
     fprintf(fd, 'position 6 -1 0\n');
     fprintf(fd, '}\n');
%endfunction

%function writevrmlnavinfo(fd)

	%fprintf('\n')

%%endfunction

function writevrmldefsphere(fd)
    fprintf(fd, 'Shape {\n');
        fprintf(fd, 'geometry DEF sphere1 Sphere {\n');
        fprintf(fd, '}\n');
        fprintf(fd, 'appearance Appearance {\n');
          fprintf(fd, 'material Material {\n');
            fprintf(fd, 'diffuseColor 0.1 0.5 1\n');
          fprintf(fd, '}\n');
        fprintf(fd, '}\n');
      fprintf(fd, '}\n');
%endfunction

function writevrmlobject(fd, x, y,z,t)

	fprintf(fd, 'Transform {\n');
        fprintf(fd, 'rotation 0 1 0 1.57\n');
        fprintf(fd, 'translation %f %f %f\n',x,y,z);
        fprintf(fd, 'children [\n');
         fprintf(fd, 'Shape {\n');
        %fprintf(fd, 'geometry USE sphere1 Sphere {\n');
        fprintf(fd, 'geometry USE sphere1\n');
        %fprintf(fd, '}\n');
        fprintf(fd, 'appearance Appearance {\n');
          fprintf(fd, 'material Material {\n');
            fprintf(fd, 'diffuseColor 0.1 0.5 %f\n',t/20.0);
          fprintf(fd, '}\n');
        fprintf(fd, '}\n');
			fprintf(fd, '}\n');
         fprintf(fd, ']\n');
      fprintf(fd, '}\n');


%endfunction





