function [userdetails]=userdetails(textdata)
% return cell array of username and user group from input cellearray
% generated by text data from qacct and imported into matlab


    [nusers,ninfo]=size(textdata);
    userdetails=cell(nusers-2,2);
    
    if ninfo>=1       
        for i=1:nusers-2
          username=sprintf('%s',textdata{i+2,1});
          userdetails{i,1}=sprintf('%s',username);
          usergroup=sprintf('%c%c',username(1),username(2));                        
          userdetails{i,2}=sprintf('%s', usergroup);
        end
    end
   
%endfunction